# Generated by Django 5.2.5 on 2025-09-05 04:15

import gag.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=gag.helpers.UploadTo('profile')),
        ),
    ]
